[project]
name = "cs50"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "check50>=3.4.0",
    "pygame>=2.6.1",
    "style50>=2.10.4",
    "submit50>=3.2.1",
]
